export interface IAmineTreatmentResult {
  feed_gas_mol_weight: number,
  lean_amine_mol_weight: number,
  feed_gas_mass_density: number,
  lean_amine_mass_density: number,
  sweet_gas_temperature: number,
  sweet_gas_mol_flow: number,
  rich_amine_mol_flow: number,
  rich_amine_temperature: number,
  rich_amine_h2s_mol_flow: number,
  sweet_gas_h2s_mol_flow: number,
  rich_amine_co2_mol_flow: number,
  sweet_gas_co2_mol_flow: number,
  sweet_gas_mol_weight: number,
  rich_amine_mol_weight: number,
}
